import { useEffect, useRef, useState } from 'react'
import { loadDiscussionEvents } from '../storage/db'
import type { DiscussionCommand, DiscussionEvent } from '../types/discussion'

type Status='idle'|'connecting'|'connected'|'reconnecting'|'finished'|'failed'
function wsUrl(){const explicit=import.meta.env.VITE_WS_BASE_URL;const token=import.meta.env.VITE_API_TOKEN?`?token=${encodeURIComponent(String(import.meta.env.VITE_API_TOKEN))}`:'';if(explicit)return `${explicit.replace(/\/$/,'')}/discussion/ws${token}`;const url=new URL(import.meta.env.VITE_API_BASE_URL??'/api',location.origin);url.protocol=url.protocol==='https:'?'wss:':'ws:';return `${url.toString().replace(/\/$/,'')}/discussion/ws${token}`}
export function useDiscussionSocket({topic,dataSummary,sessionId,lastEventSeq,onSession,onEvent}:{topic:string;dataSummary:string;sessionId:string|null;lastEventSeq:number;onSession:(id:string)=>void;onEvent:(event:DiscussionEvent)=>Promise<void>}){
  const[status,setStatus]=useState<Status>('idle');const[events,setEvents]=useState<DiscussionEvent[]>([]);const[error,setError]=useState<string|null>(null);const[attempt,setAttempt]=useState(0);const socket=useRef<WebSocket|null>(null);const lastSeq=useRef(lastEventSeq);const activeSession=useRef(sessionId??crypto.randomUUID());const finished=useRef(false);const needRecover=useRef(false)
  const inputs=useRef({topic,dataSummary,sessionId,onSession,onEvent})
  useEffect(()=>{inputs.current={topic,dataSummary,sessionId,onSession,onEvent}},[topic,dataSummary,sessionId,onSession,onEvent])
  useEffect(()=>{lastSeq.current=lastEventSeq},[lastEventSeq]);useEffect(()=>{if(sessionId)activeSession.current=sessionId},[sessionId]);useEffect(()=>{if(sessionId)void loadDiscussionEvents(sessionId).then(value=>setEvents(value))},[sessionId])
  useEffect(()=>{if(finished.current||attempt>5)return;queueMicrotask(()=>setStatus(attempt?'reconnecting':'connecting'));const ws=new WebSocket(wsUrl());socket.current=ws;ws.onopen=()=>{setStatus('connected');setError(null);const id=activeSession.current;const current=inputs.current;if(current.sessionId&&needRecover.current){needRecover.current=false;ws.send(JSON.stringify({type:'recover',session_id:id,client_message_id:crypto.randomUUID()} satisfies DiscussionCommand))}const command:DiscussionCommand=current.sessionId?{type:'resume',session_id:id,client_message_id:crypto.randomUUID(),last_event_seq:lastSeq.current}:{type:'start',session_id:id,client_message_id:crypto.randomUUID(),topic:current.topic,data_summary:current.dataSummary};if(!current.sessionId)current.onSession(id);ws.send(JSON.stringify(command))};ws.onmessage=message=>{try{const parsed=JSON.parse(String(message.data)) as DiscussionEvent;if(parsed.type==='error'&&parsed.event_seq===0){setError(parsed.error?.message??'研讨协议错误');setStatus('failed');finished.current=true;return}if(parsed.type==='error')needRecover.current=parsed.recoverable===true;if(parsed.event_seq<=lastSeq.current)return;if(parsed.event_seq>lastSeq.current+1){ws.close();return}lastSeq.current=parsed.event_seq;setEvents(current=>[...current,parsed]);void inputs.current.onEvent(parsed);if(parsed.type==='finished'){finished.current=true;setStatus('finished');ws.close()}else if(parsed.type==='error'&&!parsed.recoverable){finished.current=true;setError(parsed.error?.message??'研讨失败');setStatus('failed')}}catch{setError('收到无法识别的研讨消息')}};ws.onerror=()=>setError('研讨连接中断');ws.onclose=()=>{if(finished.current)return;const delay=2**attempt*1000;window.setTimeout(()=>setAttempt(value=>value+1),delay)};return()=>{ws.onclose=null;ws.close()}},[attempt])
  const transmit=(command:DiscussionCommand):boolean=>{if(socket.current?.readyState===WebSocket.OPEN){socket.current.send(JSON.stringify(command));return true}return false}
  const sendMessage=(content:string)=>transmit({type:'message',session_id:activeSession.current,client_message_id:crypto.randomUUID(),content})
  const finish=()=>transmit({type:'finish',session_id:activeSession.current,client_message_id:crypto.randomUUID()})
  const retry=()=>{finished.current=false;setAttempt(value=>value>=5?0:value+1)}
  return{status,events,error,sendMessage,finish,retry}
}
