import { createContext, useContext, useEffect, useMemo, useReducer, useState, type ReactNode } from 'react'
import type { EChartsOption } from 'echarts'
import { getConfig } from '../api/config'
import { getDataset, uploadData } from '../api/data'
import { errorMessage } from '../api/client'
import type { DatasetResponse, DiscussionSummary, PPTResult } from '../types/api'
import type { DiscussionEvent } from '../types/discussion'
import { clearProject, loadDataset, loadProjectState, saveChartImage, saveDataset, saveDiscussionEvent, saveProjectState } from '../storage/db'
import { createInitialState, wizardReducer } from './wizardReducer'
import type { WizardState } from './wizardTypes'

interface WizardValue {state:WizardState;notice:string|null;setConfigStatus:(status:WizardState['configStatus'])=>void;setTopic:(topic:string)=>void;storeDataset:(dataset:DatasetResponse,file:File,dataRef?:string)=>Promise<string>;confirmDataset:()=>void;appendEvent:(event:DiscussionEvent)=>Promise<void>;setSession:(id:string)=>void;setSummary:(summary:DiscussionSummary)=>void;setChart:(option:EChartsOption,blob:Blob)=>Promise<void>;setPpt:(result:PPTResult)=>void;reset:()=>Promise<void>}
const Context=createContext<WizardValue|null>(null)
const STORAGE_KEY='qcmaker_wizard'

export function WizardProvider({children}:{children:ReactNode}){
  const[state,dispatch]=useReducer(wizardReducer,undefined,createInitialState);const[notice,setNotice]=useState<string|null>(null)
  useEffect(()=>{void(async()=>{try{const saved=JSON.parse(sessionStorage.getItem(STORAGE_KEY)??'{}') as Partial<WizardState>;const projectId=saved.currentProjectId??crypto.randomUUID();const project=await loadProjectState(projectId);let hydrated:Partial<WizardState>={...saved,currentProjectId:projectId,discussionSummary:project?.discussionSummary??null,chartOption:project?.chartOption??null,pptResult:project?.pptResult??null};if(saved.dataRef){const local=await loadDataset(saved.dataRef);if(local){try{const remote=await getDataset(local.dataset_id);hydrated={...hydrated,datasetRevision:remote.revision,dataConfirmed:remote.confirmed_revision===remote.revision}}catch(error){if(typeof error==='object'&&error!==null&&'code'in error&&error.code==='SESSION_NOT_FOUND'){const fresh=await uploadData(new File([local.sourceFile],local.filename));await saveDataset({...local,dataset_id:fresh.dataset_id,revision:fresh.revision,columns:fresh.columns,rows:fresh.rows,report:fresh.report,updatedAt:Date.now()});hydrated={...hydrated,datasetRevision:fresh.revision,dataConfirmed:false,discussionSummary:null,chartOption:null,chartImageRef:null,pptResult:null};setNotice('数据集已过期，已从本地原文件重新上传，请重新确认数据')}}}else hydrated={...hydrated,dataRef:null,datasetRevision:null,dataConfirmed:false}}dispatch({type:'HYDRATE_SUCCESS',payload:hydrated})}catch(error){setNotice(`恢复项目失败：${errorMessage(error)}`);dispatch({type:'HYDRATE_FAILED'})}try{dispatch({type:'SET_CONFIG_STATUS',payload:(await getConfig()).status})}catch{dispatch({type:'SET_CONFIG_STATUS',payload:'degraded'})}})()},[])
  useEffect(()=>{if(state.hydration!=='ready')return;const light={currentProjectId:state.currentProjectId,topic:state.topic,dataRef:state.dataRef,datasetRevision:state.datasetRevision,dataConfirmed:state.dataConfirmed,discussionSessionId:state.discussionSessionId,lastEventSeq:state.lastEventSeq,chartImageRef:state.chartImageRef,currentPath:location.pathname};sessionStorage.setItem(STORAGE_KEY,JSON.stringify(light))},[state])
  const persistProject=(next:{discussionSummary?:DiscussionSummary|null;chartOption?:EChartsOption|null;pptResult?:PPTResult|null})=>saveProjectState({projectId:state.currentProjectId,discussionSummary:next.discussionSummary??state.discussionSummary,chartOption:next.chartOption??state.chartOption,pptResult:next.pptResult??state.pptResult,updatedAt:Date.now()}).catch(()=>setNotice('当前成果暂未持久化，刷新页面可能丢失'))
  const value=useMemo<WizardValue>(()=>({state,notice,setConfigStatus:(status)=>dispatch({type:'SET_CONFIG_STATUS',payload:status}),setTopic:(topic)=>dispatch({type:'SET_TOPIC',payload:topic}),storeDataset:async(dataset,file,existing)=>{const dataRef=existing??crypto.randomUUID();await saveDataset({dataRef,projectId:state.currentProjectId,dataset_id:dataset.dataset_id,revision:dataset.revision,filename:dataset.filename,sourceFile:file,columns:dataset.columns,rows:dataset.rows,report:dataset.report,updatedAt:Date.now()});dispatch({type:'SET_DATA_REF',payload:{dataRef,revision:dataset.revision}});return dataRef},confirmDataset:()=>dispatch({type:'CONFIRM_DATA'}),appendEvent:async(event)=>{await saveDiscussionEvent(event);dispatch({type:'APPEND_DISCUSSION_EVENT',payload:event});if(event.summary)void persistProject({discussionSummary:event.summary,chartOption:null,pptResult:null})},setSession:(id)=>dispatch({type:'SET_DISCUSSION_SESSION',payload:id}),setSummary:(summary)=>{dispatch({type:'SET_DISCUSSION_SUMMARY',payload:summary});void persistProject({discussionSummary:summary,chartOption:null,pptResult:null})},setChart:async(option,blob)=>{const imageRef=crypto.randomUUID();await saveChartImage({chartImageRef:imageRef,projectId:state.currentProjectId,blob,mimeType:blob.type,updatedAt:Date.now()});dispatch({type:'SET_CHART',payload:{option,imageRef}});void persistProject({chartOption:option,pptResult:null})},setPpt:(result)=>{dispatch({type:'SET_PPT_RESULT',payload:result});void persistProject({pptResult:result})},reset:async()=>{await clearProject(state.currentProjectId);dispatch({type:'RESET_PROJECT',payload:crypto.randomUUID()})}}),[state,notice])
  return <Context.Provider value={value}>{children}</Context.Provider>
}
export function useWizard(){const value=useContext(Context);if(!value)throw new Error('WizardProvider missing');return value}
