import { ApiOutlined, CheckCircleOutlined, CloudServerOutlined, LinkOutlined, ReloadOutlined, SaveOutlined } from '@ant-design/icons'
import { Alert, AutoComplete, Button, Card, Form, Input, InputNumber, Select, Skeleton, Space, Statistic, Tag, Tooltip, message } from 'antd'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router'
import { checkConnectivity, getConfig, getModels, getProviders, getUsage, updateConfig } from '../api/config'
import { errorMessage } from '../api/client'
import { StepPage } from '../components/StepPage'
import { useWizard } from '../context/WizardContext'
import type { ConfigUpdate, ConfigView, ModelProvider, UsageView } from '../types/api'

const regionName={cn:'国内服务',global:'国际服务',local:'本地运行',custom:'自定义'}

export function ConfigPage(){
  const[form]=Form.useForm<ConfigUpdate>();const[config,setConfig]=useState<ConfigView|null>(null);const[usage,setUsage]=useState<UsageView|null>(null);const[providers,setProviders]=useState<ModelProvider[]>([]);const[models,setModels]=useState<string[]>([]);const[modelsFetchedAt,setModelsFetchedAt]=useState<Date|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[modelLoading,setModelLoading]=useState(false);const navigate=useNavigate();const{setConfigStatus}=useWizard();const providerId=Form.useWatch('llm_provider',form)??'openai';const provider=providers.find(item=>item.id===providerId)
  useEffect(()=>{void Promise.all([getConfig(),getUsage(),getProviders()]).then(([c,u,p])=>{setConfig(c);setUsage(u);setProviders(p);const local=c.llm_provider==='ollama';form.setFieldsValue({...c,llm_provider:c.llm_provider,openai_base_url:local?c.local_llm_url:c.openai_base_url,openai_model:local?c.local_llm_model:c.openai_model,openai_api_key:'',tavily_api_key:''})}).catch(e=>message.error(errorMessage(e))).finally(()=>setLoading(false))},[form])
  const providerOptions=useMemo(()=>Object.entries(regionName).map(([region,label])=>({label,options:providers.filter(item=>item.region===region).map(item=>({label:item.name,value:item.id}))})).filter(group=>group.options.length),[providers])
  const chooseProvider=(id:string)=>{const next=providers.find(item=>item.id===id);if(!next)return;form.setFieldsValue({llm_provider:id,openai_base_url:next.base_url,openai_model:'',openai_api_key:''});setModels([]);setModelsFetchedAt(null)}
  const loadModels=async()=>{const values=form.getFieldsValue();const selectedProvider=values.llm_provider??'openai';const hasSavedKey=Boolean(config?.has_openai_key&&config.llm_provider===selectedProvider);if(selectedProvider!=='ollama'&&!values.openai_api_key&&!hasSavedKey){message.warning('请先填写该服务商的 API Key，再联网获取模型');return}setModelLoading(true);try{const result=await getModels({provider:selectedProvider,base_url:values.openai_base_url,api_key:values.openai_api_key||undefined});setModels(result.models);setModelsFetchedAt(new Date());message.success(`已从厂商接口获取 ${result.models.length} 个模型`)}catch(e){setModels([]);setModelsFetchedAt(null);message.error(errorMessage(e))}finally{setModelLoading(false)}}
  const save=async(values:ConfigUpdate)=>{setSaving(true);try{const local=values.llm_provider==='ollama';const next=await updateConfig({...values,use_local_llm:local,local_llm_url:local?values.openai_base_url:undefined,local_llm_model:local?values.openai_model:undefined});setConfig(next);setConfigStatus(next.status);message.success('模型服务已保存并立即生效');navigate('/topic')}catch(e){message.error(errorMessage(e))}finally{setSaving(false)}}
  const check=async()=>{try{const values=form.getFieldsValue();const result=await checkConnectivity({provider:values.llm_provider??'openai',base_url:values.openai_base_url,api_key:values.openai_api_key||undefined,model:values.openai_model});message.success(`${result.model} · ${result.latency_ms}ms`)}catch(e){message.error(errorMessage(e))}}
  return <StepPage eyebrow="01 · SYSTEM" title="模型与预算" description="接入主流国内外模型服务；模型清单从厂商实时读取，也可手工填写新模型。" aside={config&&<Tag color={config.status==='ready'?'success':'warning'}>{config.status==='ready'?'服务就绪':'等待配置'}</Tag>} actions={<><Button icon={<ApiOutlined/>} onClick={()=>void check()}>测试连接</Button><Button type="primary" icon={<SaveOutlined/>} loading={saving} onClick={()=>form.submit()}>保存并继续</Button></>}>
    {loading&&<Skeleton active/>}<div className="config-grid" style={{display:loading?'none':undefined}}><Card className="panel-card provider-card" title={<span><CloudServerOutlined/> 模型服务</span>} extra={<Tag>{providers.length} 家服务商</Tag>}><Form form={form} layout="vertical" onFinish={save} requiredMark={false}>
      <Form.Item name="llm_provider" label="模型服务商" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={providerOptions} onChange={chooseProvider}/></Form.Item>
      <div className="provider-meta"><span className={`region-mark region-mark--${provider?.region??'custom'}`}>{provider?regionName[provider.region]:'自定义'}</span><span>{provider?.api_style==='ollama'?'本地模型仓库':'厂商官方接口'}</span>{provider?.key_url&&<a href={provider.key_url} target="_blank" rel="noreferrer"><LinkOutlined/> 获取密钥</a>}{provider?.docs_url&&<a href={provider.docs_url} target="_blank" rel="noreferrer">接口文档</a>}</div>
      <Form.Item name="openai_base_url" label="API 地址" rules={[{required:true,message:'请输入厂商 API 地址'}]}><Input placeholder="https://…/v1"/></Form.Item>
      {providerId!=='ollama'&&<Form.Item name="openai_api_key" label="API Key" rules={[{required:!(config?.has_openai_key&&config.llm_provider===providerId),message:'切换服务商时请输入对应的 API Key'}]} extra={config?.has_openai_key&&config.llm_provider===providerId?'已配置；留空表示不修改':'密钥仅保存在本机，不通过查询接口回显'}><Input.Password placeholder={config?.has_openai_key&&config.llm_provider===providerId?'已配置（不显示）':'输入后点击模型名称联网获取'}/></Form.Item>}
      <Form.Item name="openai_model" label={<span>模型名称 <small className="field-hint">点击输入框获取厂商模型</small></span>} rules={[{required:true,message:'请选择或输入模型名称'}]}><AutoComplete options={models.map(value=>({value,label:value}))} filterOption={(input,option)=>String(option?.value??'').toLowerCase().includes(input.toLowerCase())} onFocus={()=>{if(!modelLoading)void loadModels()}}><Input suffix={<Tooltip title="刷新厂商模型"><Button type="text" size="small" className="model-refresh" loading={modelLoading} icon={<ReloadOutlined/>} onClick={event=>{event.preventDefault();event.stopPropagation();void loadModels()}} aria-label="刷新厂商模型"/></Tooltip>} placeholder="选择或手工输入模型 ID"/></AutoComplete></Form.Item>
      {modelsFetchedAt&&<div className="model-source"><i className="is-live"/>厂商实时清单 · {modelsFetchedAt.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} 获取</div>}
      <Form.Item name="tavily_api_key" label="Tavily Key（可选）" extra={config?.has_tavily_key?'已配置；留空表示不修改':'用于研究员联网检索'}><Input.Password/></Form.Item><Form.Item name="max_budget_usd" label="预算上限（USD）"><InputNumber min={0} precision={2} style={{width:160}}/></Form.Item>
    </Form></Card><Card className="panel-card usage-card" title="本次预算"><Space orientation="vertical" size={18} style={{width:'100%'}}><Statistic title="剩余额度" value={usage?.remaining_usd??'—'} prefix="$"/><div className="usage-meter"><i style={{width:`${usage?Math.min(100,Number(usage.known_cost_usd)/Math.max(.01,Number(usage.budget_usd))*100):0}%`}}/></div><div className="metric-row"><span>已结算 <b>${usage?.known_cost_usd??'0'}</b></span><span>预留 <b>${usage?.reserved_usd??'0'}</b></span></div>{usage?.unknown_cost&&<Alert type="warning" showIcon message="存在待核对费用"/>}<div className="provider-count"><b>{providers.filter(item=>item.region==='cn').length}</b><span>国内</span><b>{providers.filter(item=>item.region==='global').length}</b><span>国际</span></div><div className="security-note"><CheckCircleOutlined/> 密钥不回显 · 模型实时发现 · 预算事务锁</div></Space></Card></div>
  </StepPage>
}
