import { DisconnectOutlined, SendOutlined, StopOutlined, SyncOutlined } from '@ant-design/icons'
import { Alert, Button, Empty, Input, Tag } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router'
import { AgentAvatar, agentMeta } from '../components/AgentAvatar'
import { StepPage } from '../components/StepPage'
import { useWizard } from '../context/WizardContext'
import { useDiscussionSocket } from '../hooks/useDiscussionSocket'
import { loadDataset } from '../storage/db'
import type { DiscussionEvent } from '../types/discussion'
export function DiscussionPage(){const{state,setSession,appendEvent}=useWizard();const[dataSummary,setDataSummary]=useState('已确认数据');const[input,setInput]=useState('');const navigate=useNavigate();useEffect(()=>{if(state.dataRef)void loadDataset(state.dataRef).then(data=>{if(data)setDataSummary(`共 ${data.rows.length} 行、${data.columns.length} 列；字段：${data.columns.map(c=>c.name).join('、')}`)})},[state.dataRef]);const onEvent=useCallback((event:DiscussionEvent)=>appendEvent(event),[appendEvent]);const socket=useDiscussionSocket({topic:state.topic??'',dataSummary,sessionId:state.discussionSessionId,lastEventSeq:state.lastEventSeq,onSession:setSession,onEvent});const messages=socket.events.filter(event=>event.type==='agent_message');const canWrite=socket.status==='connected';return <StepPage wide eyebrow="04 · DISCUSS" title="多角色研讨" description="主持、研究、分析与反方评审共同收敛问题；事件按序持久化。" aside={<Tag color={socket.status==='connected'?'success':socket.status==='reconnecting'?'warning':socket.status==='finished'?'blue':'default'}>{socket.status}</Tag>} actions={<>{socket.status==='failed'&&<Button icon={<SyncOutlined/>} onClick={socket.retry}>重新连接</Button>}<Button type="primary" icon={<StopOutlined/>} disabled={!canWrite} onClick={socket.finish}>结束研讨</Button></>}>{socket.error&&<Alert type="error" showIcon message={socket.error} icon={<DisconnectOutlined/>}/>}<div className="discussion-grid"><section className="discussion-stream">{messages.length===0?<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="正在组织第一轮研讨…"/>:messages.map(event=>{const role=event.agent??'moderator';const meta=agentMeta(role);return <article className="agent-message" key={event.event_seq}><AgentAvatar role={role}/><div><header><b>{meta.label}</b><span>#{event.event_seq}</span></header><p>{event.content}</p></div></article>})}<div className="discussion-composer"><Input value={input} disabled={!canWrite} placeholder="补充现场信息或要求进一步分析" onChange={e=>setInput(e.target.value)} onPressEnter={()=>{if(input.trim()){socket.sendMessage(input.trim());setInput('')}}}/><Button type="primary" icon={<SendOutlined/>} disabled={!canWrite||!input.trim()} onClick={()=>{socket.sendMessage(input.trim());setInput('')}} aria-label="发送补充信息"/></div></section><aside className="round-panel"><span>SESSION</span><code>{state.discussionSessionId?.slice(0,12)??'creating'}…</code><div className="event-counter"><b>{state.lastEventSeq}</b><small>已确认事件</small></div>{state.discussionSummary?<div className="summary-ready"><b>纪要已生成</b><p>{state.discussionSummary.summary}</p><Button type="link" onClick={()=>navigate('/visualization')}>进入图表设计 →</Button></div>:<ol><li>主持人界定范围</li><li>研究员补充资料</li><li>分析师核验数据</li><li>评审员提出质疑</li></ol>}</aside></div></StepPage>}

