import { CheckCircleOutlined, DownloadOutlined, FilePptOutlined, RocketOutlined } from '@ant-design/icons'
import { Alert, Button, Card, Input, List, Tag, message } from 'antd'
import { useEffect, useMemo, useState } from 'react'
import { generatePpt, getPptDownloadUrl } from '../api/ppt'
import { errorMessage } from '../api/client'
import { StepPage } from '../components/StepPage'
import { useWizard } from '../context/WizardContext'
import { loadChartImage, loadDataset } from '../storage/db'
const blobBase64=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',',2)[1]??'');reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})
export function PPTPage(){const{state,setPpt}=useWizard();const[name,setName]=useState((state.topic??'QC成果').slice(0,20));const[dataSummary,setDataSummary]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{if(state.dataRef)void loadDataset(state.dataRef).then(data=>{if(data){const numeric=data.columns.filter(c=>c.inferred_type==='number').map(c=>c.name);setDataSummary(`数据共 ${data.rows.length} 行、${data.columns.length} 列；字段包括 ${data.columns.map(c=>c.name).join('、')}；数值字段：${numeric.join('、')||'无'}`)}})},[state.dataRef]);const checklist=useMemo(()=>[{label:'课题',ok:Boolean(state.topic)},{label:'已确认数据',ok:state.dataConfirmed},{label:'结构化研讨纪要',ok:Boolean(state.discussionSummary)},{label:'图表图片',ok:Boolean(state.chartImageRef)}],[state]);const ready=checklist.every(item=>item.ok);const create=async()=>{if(!ready||!state.topic||!state.discussionSummary||!state.chartImageRef)return;setBusy(true);try{const stored=await loadChartImage(state.chartImageRef);if(!stored)throw new Error('图表图片已丢失，请返回上一步重新确认');if(stored.blob.size>5*1024*1024)throw new Error('图表图片超过 5MB');const result=await generatePpt({project_name:name,topic:state.topic,data_summary:dataSummary,discussion_summary:state.discussionSummary,chart_images:[await blobBase64(stored.blob)]});setPpt(result);message.success('QC 成果文件已生成')}catch(e){message.error(errorMessage(e))}finally{setBusy(false)}};return <StepPage eyebrow="06 · DELIVER" title="生成 QC 成果" description="将本次课题、数据口径、研讨纪要和图表装配为六页中文成果。" actions={<>{state.pptResult&&<Button icon={<DownloadOutlined/>} href={getPptDownloadUrl(state.pptResult.file_id)}>下载 PPT</Button>}<Button type="primary" icon={<RocketOutlined/>} disabled={!ready} loading={busy} onClick={()=>void create()}>生成 PPT</Button></> }><div className="ppt-layout"><Card className="deliver-card"><div className="ppt-icon"><FilePptOutlined/></div><label>成果名称</label><Input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/><List className="deliver-list" dataSource={checklist} renderItem={item=><List.Item><span>{item.label}</span>{item.ok?<Tag color="success" icon={<CheckCircleOutlined/>}>已就绪</Tag>:<Tag>缺失</Tag>}</List.Item>}/>{!ready&&<Alert type="warning" showIcon message="请先补齐全部流程成果"/>}{state.pptResult&&<Alert type="success" showIcon message={state.pptResult.display_name} description={`有效期至 ${new Date(state.pptResult.expires_at).toLocaleString()}`}/>}</Card><section className="slide-preview"><header><span>6 SLIDES</span><b>QC 成果结构</b></header>{['课题简介','现状与数据','原因分析','对策与建议','数据图表','总结'].map((title,index)=><article key={title}><i>{String(index+1).padStart(2,'0')}</i><div><small>QC REPORT</small><b>{title}</b></div></article>)}</section></div></StepPage>}
