import { ArrowRightOutlined, CheckOutlined, SendOutlined } from '@ant-design/icons'
import { Button, Empty, Input, Modal, Spin, message } from 'antd'
import { useState } from 'react'
import { useNavigate } from 'react-router'
import { topicChat } from '../api/topic'
import { errorMessage } from '../api/client'
import { StepPage } from '../components/StepPage'
import { useWizard } from '../context/WizardContext'
import type { ChatMessage } from '../types/api'
export function TopicPage(){const{state,setTopic}=useWizard();const[history,setHistory]=useState<ChatMessage[]>(state.topic?[{role:'assistant',content:state.topic}]:[]);const[input,setInput]=useState('');const[busy,setBusy]=useState(false);const[open,setOpen]=useState(false);const[finalTopic,setFinalTopic]=useState(state.topic??'');const navigate=useNavigate();const send=async()=>{const text=input.trim();if(!text)return;const next=[...history,{role:'user' as const,content:text}];setHistory(next);setInput('');setBusy(true);try{const result=await topicChat(text,history);setHistory([...next,{role:'assistant',content:result.response}])}catch(e){message.error(errorMessage(e))}finally{setBusy(false)}};const confirm=()=>{const suggestion=[...history].reverse().find(item=>item.role==='assistant')?.content??'';setFinalTopic(state.topic??suggestion.slice(0,120));setOpen(true)};return <StepPage eyebrow="02 · DEFINE" title="界定课题" description="先把现象说清楚，再将它收敛为可量化、可执行的 QC 课题。" actions={<Button type="primary" icon={<CheckOutlined/>} disabled={!history.some(item=>item.role==='assistant')} onClick={confirm}>确认课题</Button>}><div className="topic-workbench"><section className="conversation"><div className="conversation-head"><span className="live-dot"/>QC 课题顾问 <small>依据活动程序提供建议</small></div><div className="messages">{history.length===0&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="描述一个现场问题，例如：泵站设备故障次数偏高"/>}{history.map((item,index)=><div key={index} className={`bubble bubble--${item.role}`}><span>{item.role==='assistant'?'顾问':'我'}</span><p>{item.content}</p></div>)}{busy&&<div className="typing"><Spin size="small"/> 正在梳理问题边界</div>}</div><div className="composer"><Input.TextArea value={input} autoSize={{minRows:2,maxRows:4}} placeholder="补充对象、现状、目标或时间范围…" onChange={e=>setInput(e.target.value)} onPressEnter={e=>{if(!e.shiftKey){e.preventDefault();void send()}}}/><Button type="primary" icon={<SendOutlined/>} onClick={()=>void send()} loading={busy} aria-label="发送消息"/></div></section><aside className="method-strip"><b>课题命名检查</b><ol><li><span>01</span>对象是否明确</li><li><span>02</span>问题是否可测</li><li><span>03</span>目标是否可验证</li></ol><blockquote>对象 + 问题 + 改善方向</blockquote></aside></div><Modal title="确认最终课题" open={open} onCancel={()=>setOpen(false)} onOk={()=>{if(!finalTopic.trim())return;setTopic(finalTopic.trim());setOpen(false);navigate('/data')}} okText="确认并进入数据" okButtonProps={{icon:<ArrowRightOutlined/>}}><Input.TextArea value={finalTopic} onChange={e=>setFinalTopic(e.target.value)} rows={4} maxLength={120} showCount/><p className="modal-hint">修改已有课题将清空后续数据、研讨、图表与 PPT 成果。</p></Modal></StepPage>}

